config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # login as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'pages#home'
  get '/privacy', to: 'pages#privacy'

  resources :users, only: [:show, :edit, :update]

  resources :websites, only: [:show, :update] do
    resources :articles, only: [:index, :show]
  end

  resources :articles, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :articles, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :website
  has_many :favorites
  has_many :likes
  has_many :favorite_users, through: :favorites, source: :user
  has_many :like_users, through: :likes, source: :user
  validates :content, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/articles_controller.rb
require 'json'
require 'open-uri'
require 'wikipedia'
require 'news-api'

class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @articles = Article.includes(:likes).where(likes: { id: nil })
    @articles.destroy_all
    @website = Website.find(params[:website_id])
    # @articles = Article.where(website_id: @website.id).includes(:likes).where(likes: { id: nil })

    if @website.name == "The New York Times"
      nytimes_url = "https://api.nytimes.com/svc/search/v2/articlesearch.json?q=#{@website.keyword}&api-key=#{ENV['ny_times_api_key']}"
      nytimes_serialized = open(nytimes_url).read
      @keyword_articles = JSON.parse(nytimes_serialized)
      @keyword_articles["response"]["docs"].each do |article|
        @article = Article.new(
          website: @website,
          name: article["headline"]["main"],
          summary: article["abstract"],
          content: article["lead_paragraph"],
          url: article["web_url"]
          # image: "https://www.nytimes.com/" + article["multimedia"][0]["url"]
        )
        unless article["multimedia"].nil?
          @article.update(image: "https://www.nytimes.com/" + article["multimedia"][0]["url"])
        end
        @article.valid? ? @article.save : @article
      end
    elsif @website.name == "Wikipedia"
      @page = Wikipedia.find(@website.keyword)
      @article = Article.new(
        website: @website,
        name: @page.title,
        content: @page.summary,
        summary: @page.summary,
        url: @page.fullurl,
        image: @page.main_image_url
      )
      @article.valid? ? @article.save : @article
    elsif @website.name == "News API"
      case @website.keyword
      when "Japan" then @website.keyword = "jp"
      when "United States" then @website.keyword = "us"
      when "Mexico" then @website.keyword = "mx"
      when "Brazil" then @website.keyword = "br"
      when "Argentina" then @website.keyword = "ar"
      when "Colombia" then @website.keyword = "co"
      when "France" then @website.keyword = "fr"
      when "Germany" then @website.keyword = "de"
      when "India" then @website.keyword = "in"
      when "Russia" then @website.keyword = "ru"
      when "South Korea" then @website.keyword = "kr"
      when "United Kingdom" then @website.keyword = "gb"
      when "Australia" then @website.keyword = "au"
      when "UAE" then @website.keyword = "ae"
      when "Nigeria" then @website.keyword = "ng"
      when "Canada" then @website.keyword = "ca"
      when "Turkey" then @website.keyword = "tr"
      when "Poland" then @website.keyword = "pl"
      when "Malaysia" then @website.keyword = "my"
      when "Philippines" then @website.keyword = "ph"
      when "Ukraine" then @website.keyword = "ua"
      end
      news_api_url = "https://newsapi.org/v2/top-headlines?country=#{@website.keyword}&apiKey=#{ENV['news_api_api_key']}"
      news_api_serialized = open(news_api_url).read
      @country_articles = JSON.parse(news_api_serialized)["articles"]
      @country_articles.each do |article|
        if @website.keyword == "jp" || @website.keyword == "ru" || @website.keyword == "kr" || @website.keyword == "ae" || @website.keyword == "ua"
          @article = Article.new(
            website: @website,
            name: article["title"],
            summary: article["description"],
            content: article["description"],
            url: article["url"],
            image: article["urlToImage"]
          )
        else
          @article = Article.new(
            website: @website,
            name: article["title"],
            summary: article["description"],
            content: article["content"],
            url: article["url"],
            image: article["urlToImage"]
          )
        end
        @article.valid? ? @article.save : @article
      end
    elsif @website.name == "COVID-19 Data"
      word_index = 1
      word_array = @website.keyword.split(" ")
      if word_array.length >= 2
        until word_index == word_array.length
          word_array.insert(word_index, "-")
          word_index += 2
        end
        @website.keyword = word_array.join
      end
      covid_url = "https://api.covid19api.com/total/country/#{@website.keyword}"
      covid_serialized = open(covid_url).read
      @covid_articles = JSON.parse(covid_serialized)
      article_number1 = 0
      @hash_confirmed = {}
      @hash_death = {}
      @hash_active = {}
      until article_number1 + 1 == @covid_articles.size
        if article_number1.zero?
          @hash_confirmed[@covid_articles[article_number1]["Date"]] = @covid_articles[article_number1]["Confirmed"].to_i
          @hash_death[@covid_articles[article_number1]["Date"]] = @covid_articles[article_number1]["Deaths"].to_i
          # elsif @covid_articles[date_number]["Deaths"].to_i < @covid_articles[date_number - 1]["Deaths"].to_i || @covid_articles[date_number]["Confirmed"].to_i < @covid_articles[date_number - 1]["Confirmed"].to_i
        elsif @covid_articles[article_number1]["Deaths"].to_i > @covid_articles[article_number1 - 1]["Deaths"].to_i && @covid_articles[article_number1]["Confirmed"].to_i > @covid_articles[article_number1 - 1]["Confirmed"].to_i && @covid_articles[article_number1 - 1]["Deaths"].to_i != 0 && @covid_articles[article_number1]["Deaths"].to_i - 10000 < @covid_articles[article_number1 - 1]["Deaths"].to_i
          # && @covid_articles[article_number1]["Confirmed"].to_i - 20000 < @covid_articles[article_number1 - 1]["Confirmed"].to_i
          @hash_confirmed[@covid_articles[article_number1]["Date"]] = @covid_articles[article_number1]["Confirmed"].to_i - @covid_articles[article_number1 - 1]["Confirmed"].to_i
          @hash_death[@covid_articles[article_number1]["Date"]] = @covid_articles[article_number1]["Deaths"].to_i - @covid_articles[article_number1 - 1]["Deaths"].to_i
        end
        # @covid_articles[date_number - 1]["Confirmed"].to_i != 0
        # || @covid_articles[date_number]["Deaths"].to_i == 0 || @covid_articles[date_number]["Confirmed"].to_i == 0
        article_number1 += 1
      end
      # date_number2 = 0
      @covid_articles.each do |article|
        # until date_number2 + 1 == @covid_articles.size
        # if date_number2.zero?
        #   @hash_active[article["Date"]] = article["Active"].to_i
        if article["Date"] != "2020-06-24T00:00:00Z"
          # && @covid_articles[date_number2]["Active"].to_i + 10000 > @covid_articles[date_number2 - 1]["Active"].to_i
          @hash_active[article["Date"]] = article["Active"].to_i

        end
      end
    end
    @articles = Article.where(website_id: @website.id).includes(:likes).where(likes: { id: nil })
  end

  def show
    @article = Article.find(params[:id])
    @like = Like.new
    @favorite = Favorite.new
    # for AJAX
    respond_to do |format|
      format.html
      format.json { render json: { article: @article } }
    end
  end

  # private

  # def article_params
  #   params.require(:article).permit(:website_id, :name, :date, :summary, :url, :content, :memo)
  # end
end

app/views/articles/index.html.erb
<h1>Search results</h1>
<% if @website.name == "COVID-19 Data" %>
  <%= link_to "Search other COVID-19 data", website_path(@website), class: "btn btn-outline-primary" %>
  <div class="COVID mt-3">
    <h3><strong>COVID-19 Data in <%= @website.keyword.capitalize %></strong></h3>
    <p> *If you see data which is significantly different from other observations, that's an outlier so please ignore it.</p>
  </div>
  <%= column_chart @hash_confirmed, xtitle: "Date", title: "Number of confirmed cases" %>
  <%= column_chart @hash_death, xtitle: "Date", title: "Number of deaths" %>
  <%= line_chart @hash_active, xtitle: "Date", title: "Number of active patients" %>
<% elsif @website.name == "Wikipedia" %>
  <%= link_to "Check this article", article_path(@article), class: "btn btn-outline-primary", target: :_blank %>
  <%= link_to "Search other articles on #{@website.name}", website_path(@website), class: "btn btn-outline-primary" %>
  <% @articles.each do |article| %>
    <div class="card-product m-3">
      <% if article.image == nil %>
        <div class="card-product-infos">
          <h2><%= link_to article.name, article_path(article), target: :_blank %></h2>
          <p><%= article.summary %></p>
        </div>
      <% else %>
        <%= image_tag article.image, alt: "article image", class: "card-product-image" %>
        <div class="card-product-infos">
          <h2><%= link_to article.name, article_path(article), target: :_blank %></h2>
          <p><%= article.summary %></p>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <%= link_to "Search other articles on #{@website.name}", website_path(@website), class: "btn btn-outline-primary" %>
  <% @articles.each do |article| %>
    <div class="card-product m-3">
      <% if article.image == nil %>
        <div class="card-product-infos">
          <h2><%= link_to article.name, article_path(article), target: :_blank %></h2>
          <p><%= article.summary %></p>
        </div>
      <% else %>
        <%= image_tag article.image, alt: "article image", class: "card-product-image" %>
        <div class="card-product-infos">
          <h2><%= link_to article.name, article_path(article), target: :_blank %></h2>
          <p><%= article.summary %></p>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<%= render "shared/footer" %>

app/views/articles/show.html.erb
<h1>Details of the article</h1>
<% if @article.image? %>
  <div class="article-show d-flex justify-content-center my-3">
    <%= image_tag @article.image, alt: "alttext", class: "article-image" %>
  </div>
<% end %>
<div class="article-content m-5">
<h5><%= @article.content %></h5>
</div>
<div class="row justify-content-center">
  <h5><%= link_to "Check this article on on the external website", @article.url, class: 'btn btn-outline-primary mx-2', target: :_blank %></h5>
  <div id="like_button_<%= @article %>">
    <h5><%= render partial: 'likes/like', locals: { article: @article} %></h5>
  </div>
  <h5><%= link_to "Check the articles you liked", user_path(current_user), class: 'btn btn-outline-primary mx-2' %></h5>
  <h5><%= link_to "Translate this article", "https://translate.google.com/?hl=en#view=home&op=translate&sl=auto&tl=en&text=#{@article.content}", target: '_blank', class: 'btn btn-outline-primary mx-2' %></h5>
</div>
<div class="likes_content d-flex justify-content-center">
  <div id="likes_number">
    <p>The number of likes: <%= @article.likes.count %></p>
  </div>
</div>
<div class="likes_content d-flex justify-content-center">
  <p>Users who liked this article</p>
  <ul>
    <% @article.like_users.each do |user| %>
      <li><%= user.name %></li>
    <% end %>
  </ul>
</div>
<div class="d-flex justify-content-center mt-2">
  <h5><strong>Share this article on SNS</strong></h5>
</div>
<div class="share-sns d-flex justify-content-center">
  <%= link_to 'Twitter', "https://twitter.com/share?url=#{@article.url}", target: '_blank', class: 'btn btn-outline-primary mx-2' %>
  <%= link_to 'Facebook', "http://www.facebook.com/share.php?u=#{@article.url}", target: '_blank', class: 'btn btn-outline-primary mx-2'%>
  <%= link_to 'LINE', "http://line.me/R/msg/text/?#{@article.url}", target: '_blank', class: 'btn btn-outline-primary mx-2' %>
  <%= link_to 'LinkedIn', "http://www.linkedin.com/shareArticle?mini=true&url=#{@article.url}", class: 'btn btn-outline-primary mx-2', target: '_blank' %>
</div>
<%= render "shared/footer" %>