config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # login as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'pages#home'
  get '/privacy', to: 'pages#privacy'

  resources :users, only: [:show, :edit, :update]

  resources :websites, only: [:show, :update] do
    resources :articles, only: [:index, :show]
  end

  resources :articles, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :articles, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(article_id: params[:article_id])
    @like.save
    respond_to do |format|
      format.html
      format.json { render json: { article: @article } }
    end
  end

  def destroy
    @like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    @like.destroy
    respond_to do |format|
      format.html
      format.json { render json: { article: @article } }
    end
  end
end

app/views/likes/_like.html.erb
<% if current_user.already_liked?(article) %>
  <%= button_to 'Unlike', article_like_path(article), class: "btn btn-outline-primary mx-2", method: :delete, remote: true  %>
<% else %>
  <%= button_to 'Like', article_likes_path(article), class: "btn btn-outline-primary mx-2", method: :post, remote: true %>
<% end %>
# changed @article to article due to the warning from rails_best_practices

app/views/likes/create.js.erb
//document.querySelector("#like_button").addEventListener("click", () => {
document.querySelector("#like_button").innerHTML = "<%=j render 'likes/like', article: @article %>"
//})

app/views/likes/destroy.js.erb
// document.querySelector("#like_button").addEventListener("click", () => {
document.querySelector("#like_button").innerHTML = "<%=j render 'likes/like', article: @article %>";
//})