config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # login as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'pages#home'
  get '/privacy', to: 'pages#privacy'

  resources :users, only: [:show, :edit, :update]

  resources :websites, only: [:show, :update] do
    resources :articles, only: [:index, :show]
  end

  resources :articles, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :articles, only: [:show] do
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable
  has_many :favorites
  has_many :likes
  has_many :favorited_articles, through: :favorites, source: :article
  has_many :liked_articles, through: :likes, source: :article
  has_one_attached :photo
  # validates :name, presence: true

  def already_liked?(article)
    self.likes.exists?(article_id: article.id)
  end

  # test user
  def self.guest
    find_by(email: 'test@example.com')
  end

  # omniauth
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        # email:    User.dummy_email(auth),
        # password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  # private

  # def send_welcome_email
  #   UserMailer.with(user: self).welcome.deliver_now
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  def github
    callback_from :github
  end

  def linkedin
    callback_from :linkedin
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    #redirect_to root_path
    redirect_back(fallback_location: root_path, notice: "Logged in as a test user")
    # add AJAX?, redirect to somewhere else
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end
end

app/views/users/edit.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="row">
    <div class="col-xs-12">
      <div class="simple-form">
        <h2>Edit your profile</h2>
          <%= simple_form_for(@user) do |f| %>
            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :email %>
              <%= f.input :photo, as: :file %>
              <%= f.submit value: "Edit profile"%>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<h1>The articles you liked</h1>
<%= link_to "Search other articles", root_path, class: "btn btn-outline-primary" %>
<% @user.liked_articles.each do |article| %>
  <div class="card-product m-3">
    <%= image_tag article.image, alt: "article image", class: "card-product-image" %>
    <div class="card-product-infos">
      <!-- article.url -->
      <!-- <h2><%#= link_to article.name, website_article_path(@website, article) %></h2> -->
      <h2><%= link_to article.name, article_path(article), target: :_blank %></h2>
      <p><%= article.summary %></p>
    </div>
  </div>
<% end %>
<%= render "shared/footer" %>